[tools]
bun = "latest"
dotnet = "latest"
eza = "latest"
go = "latest"
java = "openjdk-25.0.2"
neovim = "stable"
node = "latest"
python = "3.14"
rust = "1.93.1"
usage = "latest"
uv = "latest"
zig = "latest"
